program: main.cpp
	g++ main.cpp -o program -g -Wall -Wpedantic
	@echo =================================
	./program --ut
	@echo =================================
	./program

.PHONY: clean
clean:
	rm -v program
